config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root :to => "homes#top"

  get '/about' => 'homes#about'

  resources :books
  resources :homes
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :image
  has_many :books, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(@user.id)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def top
  end

  def index
    @books = Book.all
    # @users =  Book.find(params[:id])
    @user = current_user
  end

  def show
    @book = Book.find(params[:id])
    @books = @user.name
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user
    if @book.save
      redirect_to book_path(@book.id), notice: 'You have created book successfully.'
    else
      @books = Book.all
      render :index
    end
  end

  # def edit
  #   @book = Book.find(params[:id])
  # end

  # def update
  #   @book = Book.find(params[:id])
  #   if @book.update(book_params)
  #     redirect_to book_path(@book.id), notice: 'Book was successfully updated.'
  #   else
  #     render :edit
  #   end
  # end
  # def destroy
  #   book = Book.find(params[:id])
  #   book.destroy
  #   redirect_to '/books', notice: 'Book was successfully destroy.'
  # end

  private
  def book_params
    params.require(:book).permit(:title, :body, :user_id)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @user = current_user
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
      @users = User.all
      @user = current_user
  end

  def show
    @user = current_user
    @books = current_user.books
  end

  # def create
  # end

  def edit
    @user = current_user
  end


  def update
    @user = User.find(params[:id])
    @user.id = current_user.id
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :introduction)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<h1>books/edit</h1>

<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      <%= form_with model: @book, url: book_path(@book.id),class: 'edit_book', method: :patch do |f| %>
      <div class="form-group">
        <label for="book_title">Title</label>
        <%= f.text_field :title %>
      </div>
      <div class="form-group">
        <label for="book_title">Opinion</label>
        <%= f.text_area :opinion %>
      </div>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<%= render 'users/userinfo', users: @users %>

<div class="col-md-8 offset-md-1">
  <h2>Books</h2>
  <table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @books.each do |book| %>
        <tr>
            <td><%= link_to user.image %></td>
            <td><%= link_to book.title, "/books/#{book.id}" %></td>
            <td><%= book.body %></td>
        </tr>
        <% end %>
      </tbody>
      </table>
    </div>

app/views/books/show.html.erb
<h1>books/show</h1>

<%= render 'userinfo', post_images: @homes %>

<div class="col-md-8 offset-md-1">
    <h2>Book detail</h2>
    <table class="table">
        <tbody>
         <% @books.each do |book| %>
         <tr>
            <td><%= user.image %></td>
            <td><%= book.title %></td>
            <td><%= book.body %></td>
            <td><%= link_to 'Edit', edit_book_path ,:class 'btn btn-sm btn-success' %></td>
            <td><%= link_to 'Destroy', edit_book_path ,:class 'btn btn-sm btn-danger' %></td>
        </tr>
        <% end %>
        </tbody>
    </table>
</div>

app/views/homes/about.html.erb
  <div class="container">
    <div class="row">
      <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>
        <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      </div>
    </div>
  </div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <a class="btn btn-info btn-sm btn-block mb-3 sign_in"><%= link_to "Log in", new_user_session_path %></a>
        </div>
        <div class="row">
          <a class="btn btn-success btn-sm btn-block sign_up"><%= link_to "Sign up", new_user_registration_path %></a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <%= link_to "Bookers", "/", class: 'navbar-brand' %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="navbar-collapse collapse show" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
              <li><a class="nav-link text-light" href="/users/:id"><i class="fas fa-home"></i>Home</a></li>
              <% else %>
              <li><a class="nav-link text-light" href="/"><i class="fas fa-home"></i>Home</a></li>
              <% end %>
              <% if user_signed_in? %>
              <li><a class="nav-link text-light" href="/users"><i class="fas fa-users"></i>User</a></li>
              <% else %>
              <li><a class="nav-link text-light" href="/about"><i class="fas fa-link"></i>About</a></li>
              <% end %>
              <!--<%= link_to "Users", users_path %>-->
              <% if user_signed_in? %>
                <li><a class="nav-link text-light" href="/books"><i class="fas fa-book-open"></i>Book</a></li>
                <li><a class="nav-link text-light" href="/users/sign_out" data-method="delete"><i class="fas fa-sign-out-alt"></i>Log out</a></li>
                <li><a class="nav-link text-light"><%= link_to "",  destroy_user_session_path, method: :delete %></a></li>
              <% else %>
                <li><a class="nav-link text-light" href="/users/sign_up"><i class="fas fa-sign-in-alt"></i>Sign up</a></li>
                <li><a class="nav-link text-light" href="/users/sign_in"><i class="fas fa-user-plus"></i>Log in</a></li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main>
    <% flash.each do |key, value| %>
    <p id="notice">
      <%= value %>
    </p>
<% end %>
    <%= yield %>
    </main>
  </body>
  <footer>
    <div class='container mt-5'>
    	<div class='row'>
      	<div class='mx-auto'>
      		<p>CopyRight Infratop.inc</p>
      	</div>
      </div>
    </div>
  </footer>
</html>

app/views/users/_userinfo.html.erb
  <div class="col-md-3">
    <h2>User info</h2>
    <table>
      <tbody>
        <tr>
      	  <th>name</th>
      	  <th><%= @user.name %></th>
        </tr>
        <tr>
      	  <th>introduction</th>
      	  <th><%= @user.introduction %></th>
        </tr>
      </tbody>
    </table>
    <div class="row">
      <%= link_to 'edit', edit_user_path(@user.id) %>
    </div>
    <h2 class="mt-3">New book</h2>
    <%= form_with model: @book, url: '/books', local: true, method: :post do |f| %>
      <div class="form-group">
        <label for="book_title">Title</label>
        <%= f.text_field :title %>
      </div>
      <div class="form-group">
        <label for="book_opinion">Opinion</label>
        <%= f.text_area :opinion %>
      </div>
      <div class="form-group">
        <%= f.submit 'Create Book', class: 'btn btn-success' %>
      </div>
    <% end %>
    </div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <%= form_with model: @user, local: true do |f| %>
        <div class="form-group">
          <label for="user_name">Name</label>
          <%= f.text_field :name %>
        </div>
        <div class="form-group">
          <label for="user_image">Image</label>
          <%= f.file_field :image , class: 'form-control-file user_image', accept: "image/*" %>
        </div>
        <div class="form-group">
          <label for="user_introduction">Introduction</label>
            <%= f.text_area :introduction , class: 'form-control introduction'%>
        </div>
        <div class="form-group">
          <%= f.submit 'Update User', class: 'btn btn-secondary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<%= render 'userinfo', post_images: @homes %>

<div class="col-md-8 offset-md-1">
  <h2>Users</h2>
  <table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |users| %>
        <tr>
            <td><%= link_to users.image %></td>
            <td><%= users.name %></td>
            <td><%= link_to 'Show' , user_path(@user.id) %></td>
        </tr>
        <% end %>
      </tbody>
      </table>
    </div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
  <%= render 'userinfo', post_users: @homes %>
  <div class="col-md-8 offset-md-1">
    <h2>Books</h2>
    <table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
        </tr>
      </thead>
      <tbody>
         <% @books.each do |book| %>
         <tr>
            <td><%= user.image %></td>
            <% if @user === current_user.id %>
            <td><%= link_to book.title, "/books/#{book.id}" %></td>
            <% end %>
            <td><%= book.opinion %></td>
         </tr>
        <% end %>
      </tbody>
    </table>
</div>
  </div>
</div>

app/views/users/update.html.erb
<h1>books/index</h1>